# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitflow-helper" do
  version "0.5.49"

  on_macos do
    url "https://github.com/novaemx/gitflow-helper/releases/download/v0.5.49/gitflow-0.5.49-darwin-universal.tar.gz"
    sha256 "600819f8e7e3597dea6984b9255b2b1973ac177246dd4b570a7a6d72303d9c10"
  end

  name "gitflow-helper"
  desc "Git Flow workflow helper — interactive TUI + CLI. Only requires git."
  homepage "https://github.com/novaemx/gitflow-helper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitflow"

  # No zap stanza required

end
