# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitflow-helper" do
  version "0.5.51"

  on_macos do
    url "https://github.com/novaemx/gitflow-helper/releases/download/v0.5.51/gitflow-0.5.51-darwin-universal.tar.gz"
    sha256 "aed4e039d02a3c05329c76a2823c415910b2448628af8a45597a8a8c1310adcb"
  end

  name "gitflow-helper"
  desc "Git Flow workflow helper — interactive TUI + CLI. Only requires git."
  homepage "https://github.com/novaemx/gitflow-helper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitflow"

  # No zap stanza required

end
